spring:

  datasource:
    url: jdbc:postgresql://postgres:5432/spring_backend_lab

  data:
    redis:
      host: redis

  kafka:
    bootstrap-servers: kafka:9092

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.spring-backend-lab.ru/realms/spring-backend-lab
          jwk-set-uri: http://keycloak:8080/realms/spring-backend-lab/protocol/openid-connect/certs