--liquibase formatted sql

--changeset onidza:001-init

CREATE TABLE client_coupons (
    client_id bigint NOT NULL,
    coupon_id bigint NOT NULL
);

CREATE TABLE clients (
    id bigint NOT NULL,
    profile_id bigint NOT NULL,
    registration_date timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL
);

ALTER TABLE clients
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

CREATE TABLE coupons (
    discount real NOT NULL,
    expiration_date timestamp(6) without time zone,
    id bigint NOT NULL,
    code character varying(255) NOT NULL
);

ALTER TABLE coupons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

CREATE TABLE orders (
   total_amount numeric(38,2),
   client_id bigint NOT NULL,
   id bigint NOT NULL,
   order_date timestamp(6) without time zone,
   status character varying(255),
   CONSTRAINT orders_status_check
       CHECK (((status)::text
                   = ANY ((ARRAY['NEW'::character varying,
                       'PAID'::character varying, 'CANCELLED'::character varying])::text[])))
);

ALTER TABLE orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

CREATE TABLE profiles (
     id bigint NOT NULL,
--      address character varying(255) NOT NULL,
     phone character varying(255) NOT NULL
);

ALTER TABLE profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE ONLY client_coupons
    ADD CONSTRAINT client_coupons_pkey PRIMARY KEY (client_id, coupon_id);

ALTER TABLE ONLY clients
    ADD CONSTRAINT clients_email_key UNIQUE (email);

ALTER TABLE ONLY clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (id);

ALTER TABLE ONLY clients
    ADD CONSTRAINT clients_profile_id_key UNIQUE (profile_id);

ALTER TABLE ONLY coupons
    ADD CONSTRAINT coupons_pkey PRIMARY KEY (id);

ALTER TABLE ONLY orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);

ALTER TABLE ONLY profiles
    ADD CONSTRAINT profiles_phone_key UNIQUE (phone);

ALTER TABLE ONLY profiles
    ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY client_coupons
    ADD CONSTRAINT fk_client_coupons_client FOREIGN KEY (client_id)
        REFERENCES clients(id);

ALTER TABLE ONLY client_coupons
    ADD CONSTRAINT fk_client_coupons_coupon FOREIGN KEY (coupon_id)
        REFERENCES coupons(id);

ALTER TABLE ONLY orders
    ADD CONSTRAINT fk_orders_client FOREIGN KEY (client_id)
        REFERENCES clients(id);

ALTER TABLE ONLY clients
    ADD CONSTRAINT fk_client_profile FOREIGN KEY (profile_id)
        REFERENCES profiles(id);

































